---
- name: Deploy haproxy load balancer
  hosts: load_balancers
  gather_facts: false
  become: true
  tags:
    - load_balancers

  tasks:
    - debug:
        msg: "Start HAproxy server setup"

    - name: Setup HAproxy server
      include_role:
        name: haproxy

    - debug:
        msg: "Finished HAproxy server setup"


...
